---
- name: rc conf
  lineinfile:
    line: '{{ item }}'
    regexp: "^{{ item | regex_replace('=.*$','=') }}"
    dest: /etc/rc.conf
  with_items:
    - 'nfs_server_enable="YES"'
    - 'nfs_server_flags="{{ mynfsd_flags }}"'
    - '{% if nfsv4_enable %}nfsv4_server_enable="YES"{% else %}omit{% endif %}'
  notify: restart freebsd nfs server
  when: ansible_os_family == "FreeBSD"
  tags: nfs,rc

- name: exports
  copy:
    dest: /etc/exports
    force: no
    content: |
      V4: / -sec=sys
  tags: nfs,exports

- name: mkdir & co
  include_tasks: share.yml
  with_items:
    - '{{ shares }}'
    - '{{ group_shares }}'
  loop_control:
    loop_var: share
  when: '"nfsshares" in share'
  tags: nfs,shares

